# Generated by Django 5.2.8 on 2025-12-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposolicitud',
            name='destinatario',
            field=models.CharField(choices=[('alumno', 'Solo Alumnos'), (
                'docente', 'Solo Personal/Docentes'), ('ambos', 'Alumnos y Personal')], default='ambos', max_length=10),
        ),
    ]
