# Generated by Django 5.0.4 on 2025-11-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña en el próximo login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil_completo',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha completado su perfil'),
        ),
    ]
